config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :mailing_lists, only: [:new, :create], path: "mailing-lists"
  end
  resources :contacts
  resources :contact_uploads, only: :create
  resources :uploads, only: :destroy
  resources :mailing_lists, only: :show, path: "mailing-lists"
  resources :mailing_list_contacts, only: [:create, :update], path: "mailing-list-contacts"
  resource :mailing_list_contacts_toggle, only: [:update], path: "mailing-list-contacts-toggle"

  root to: "events#index"
end

app/models/mailing_list.rb
class MailingList < ApplicationRecord
  belongs_to :event, required: true

  has_many :mailing_list_contacts
  has_many :contacts, through: :mailing_list_contacts

  validates :title, presence: true
end

app/controllers/mailing_lists_controller.rb
class MailingListsController < ApplicationController
  def new
    render locals: {
      mailing_list: MailingList.new,
      event: event,
    }
  end

  def show
    respond_to do |format|
      format.html { render locals: { mailing_list: MailingListPresenter.new(mailing_list) } }
      format.json do
        render json: { contacts: MailingListPresenter.new(mailing_list).contacts }
      end
      format.csv do
        exporter = MailingListExport.new(mailing_list)
        send_data exporter.data, filename: exporter.filename
      end
    end
  end

  def create
    respond_to do |format|
      if new_mailing_list.save
        format.html { redirect_to new_mailing_list }
      else
        format.html do
          render :new, locals: {
            mailing_list: new_mailing_list,
            event: event,
          }
        end
      end
    end
  end

  private

  def mailing_list
    @_mailing_list ||= MailingList.find(params[:id])
  end

  def mailing_params
    params.require(:mailing_list).permit(:title).merge(event: event)
  end

  def new_mailing_list
    @_mailing_list ||= MailingList.new(mailing_params)
  end

  def event
    @_event ||= Event.find(params[:event_id])
  end
end

app/views/mailing_lists/new.html.haml
.h1.center New Mailing List
.h4.center
  = link_to event.event_title, event

= form_for [event, mailing_list] do |f|
  .field
    = f.label :title
    = f.text_field :title
    = f.inline_errors :title
  = f.button nil, class: "capitalize"

app/views/mailing_lists/show.html.haml
.max-w-lg.mx-auto
  %div{ class: "sm:flex items-center mt-4 mb-6" }
    %div{ class: "font-bold mr-2 text-4xl pb-2 sm:p-0" }= mailing_list.title
    = link_to mailing_list.event_title, mailing_list.event
    = link_to mailing_list_path(mailing_list.id, format: :csv), class: "no-underline text-grey border py-1 px-2 ml-auto rounded hover:text-white hover:bg-grey", format: :csv do
      Export
      %i{ class: "fa fa-download" }

  %div{ class: "mailing_list__contacts text-md sm:text-base", data: { turbolinks: "false" } }
    #mailing_list__contacts-list
      .flex.pt-2
        %input{ "class" => "p-2 w-full",
        "placeholder" => "Search...",
        "v-model" => "search",
        }
        .flex.pl-2
          .flex.flex-col.items-center
            .pb-1.uppercase.text-xs Filter
            %a{ class: "no-underline py-1 px-2 rounded-full border text-sm",
            "href" => "#filter",
            "@click" => "toggleAddedFilter",
            "v-bind:class" => "{ 'bg-blue text-white': filterByAdded }" } Added
          .flex.ml-2
            %a{ class: "border m-auto h-8 flex items-center justify-center no-underline rounded-full text-grey text-xl w-8",
            "href" => "#",
            "@click.prevent" => "clearFilters",
            "v-show" => "filterByAdded || search",
            }= raw("&times")
      .text-sm.pt-2
        {{ numberOfAssignedContacts }} contacts assigned to mailing list.
      .header.flex.p-2.items-end
        .flex-auto.bold Name
        %div{ class: "w-12 sm:w-24 bold text-xs sm:text-md sm:text-left text-center" }
          .block.pb-1 Add to List
          %a{ class: "block no-underline py-1 px-2 rounded-full border text-xs sm:text-sm sm:inline-block",
          href: "#toggle",
          "@click.prevent" => "toggleAddAll",
          }= "Toggle All"
        %div{ class: "w-12 sm:w-24 bold text-xs sm:text-md sm:text-left text-center" }
          .block Need
          .block Address
        %div{ class: "w-12 sm:w-24 bold text-xs sm:text-md sm:text-left text-center" }
          .block Action
          .block Complete
          .block.font-bold {{ percentComplete }}

      %ul.list-reset.my-0
        = render "mailing_list_contact_js_template"


:javascript
  window._contacts = #{raw mailing_list.contacts.to_json};
  window._mailing_list_id = #{raw mailing_list.id};