config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :mailing_lists, only: [:new, :create], path: "mailing-lists"
  end
  resources :contacts
  resources :contact_uploads, only: :create
  resources :uploads, only: :destroy
  resources :mailing_lists, only: :show, path: "mailing-lists"
  resources :mailing_list_contacts, only: [:create, :update], path: "mailing-list-contacts"
  resource :mailing_list_contacts_toggle, only: [:update], path: "mailing-list-contacts-toggle"

  root to: "events#index"
end

app/models/event.rb
class Event < ApplicationRecord
  scope :upcoming, -> { where("event_date > :date", date: Date.yesterday) }
  scope :in_the_past, -> { where("event_date < :date", date: Date.today) }
  scope :floating, -> { where(event_date: nil) }

  has_many :mailing_lists
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    render locals: {
      events: Event.upcoming.map { |e| EventDecorator.new(e) },
      previous_events: Event.in_the_past.map { |e| EventDecorator.new(e) },
      floating_events: Event.floating.map { |e| EventDecorator.new(e) },
    }
  end

  def show
    respond_to do |f|
      f.html { render locals: { event: event }}
      f.js { render locals: { event: event }}
    end
  end

  def new
    render locals: { event: Event.new }
  end

  def create
    if new_event.save
      redirect_to root_path
    end
  end

  private

  def event
    @_event ||= Event.find(params[:id])
  end

  def new_event
    @_event = Event.new(event_params)
  end

  def event_params
    params.require(:event).permit(:event_title, :event_date)
  end
end

app/views/events/_event.html.haml
%div[event]{ class: "flex" }
  .pr-1= event.event_date_formatted
  .event-title
    = link_to event.event_title, event

app/views/events/_event_group.html.haml
%div{ class: "events-group flex w-full sm:w-1/2" }
  .p-1.flex.flex-auto
    .bg-white.flex-auto.p-1.border-mid
      %h2.center.p1= title 
      = render(events) || no_events_msg

app/views/events/_show.html.haml
.h1.center= event.event_title
.mailing-list
  .h3.inline Mailing List
  = link_to "New", new_event_mailing_list_path(event)
  - event.mailing_lists.each do |list|
    .mailing_list_link
      = link_to list.title, list

app/views/events/index.html.haml
.events.flex.flex-wrap
  = render "event_group", title: "Upcoming Events", events: events, no_events_msg: "No upcoming events"
  = render "event_group", title: "Previous Events", events: previous_events, no_events_msg: "No previous events"
  = render "event_group", title: "Floating Events", events: floating_events, no_events_msg: ""

app/views/events/new.html.haml
%h1 New Event

= form_for event do |f|
  = f.text_field :event_title, placeholder: "Event Title"
  = f.date_field :event_date
  = f.submit

app/views/events/show.html.haml
= render "show", event: event

app/views/events/show.js.erb
window.modal.showWithHTML("<%= j(render "show", event: event) %>");