config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :mailing_lists, only: [:new, :create], path: "mailing-lists"
  end
  resources :contacts
  resources :contact_uploads, only: :create
  resources :uploads, only: :destroy
  resources :mailing_lists, only: :show, path: "mailing-lists"
  resources :mailing_list_contacts, only: [:create, :update], path: "mailing-list-contacts"
  resource :mailing_list_contacts_toggle, only: [:update], path: "mailing-list-contacts-toggle"

  root to: "events#index"
end

app/models/contact.rb
class Contact < ApplicationRecord
  attribute :is_complete, :boolean
  scope :by_name, -> { order(:name) }

  belongs_to :upload, optional: true
  has_many :mailing_list_contacts
  has_many :mailing_lists, through: :mailing_list_contacts
  has_many :versions, -> { order(:created_at) }, class_name: ContactVersion

  def self.new_from_csv_upload(csv_upload_contact)
    new(
      name: csv_upload_contact.name,
      street_1: csv_upload_contact.street_1,
      street_2: csv_upload_contact.street_2,
      city: csv_upload_contact.city,
      state: csv_upload_contact.state,
      zipcode: csv_upload_contact.zipcode,
      country: csv_upload_contact.country,
      upload: csv_upload_contact.upload,
    )
  end

  def full_address
    address_string = ""
    address_string += "#{street_1}" if street_1.present?
    address_string += " #{street_2}" if street_2.present?
    address_string += " #{city}" if city.present?
    address_string += " #{state}" if state.present?
    address_string += " #{zipcode}" if zipcode.present?
    address_string
  end
  alias :address :full_address

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    respond_to do |f|
      f.json { render json: Contact.all.order(:name).as_json(methods: [:address]) }
      f.html do
        render locals: {
          contacts: Contact.all.order(:name),
          last_upload: Upload.most_recent,
          recent_uploads: Upload.by_most_recent,
        }
      end
    end
  end

  def show
    render locals: { contact: contact }
  end

  def new
    render locals: { contact: Contact.new }
  end

  def create
    new_contact = Contact.new(contact_params)
    if new_contact.save
      redirect_to new_contact
    else
      ap new_contact.errors
      render :new
    end
  end

  def update
    contact.attributes = contact_params
    is_new_version = contact.changed?

    if contact.save
      ContactVersioner.new(contact) if is_new_version
      render :show, locals: { contact: contact }, alert: "Updated"
    else
      render :show, locals: { contact: contact }
    end
  end

  def destroy
    contact.destroy!
    redirect_to contacts_path
  end

  private

  def contact
    @_contact ||= ContactForm.new(Contact.find(params[:id]), Contact.all.by_name.pluck(:id))
  end

  def contact_params
    params.require(:contact).permit(
      :name,
      :street_1,
      :street_2,
      :city,
      :state,
      :zipcode,
    )
  end


  class ContactForm < SimpleDelegator

    attr_reader :contact_ids, :contact_index

    def initialize(contact, contact_ids)
      super(contact)
      @contact_ids = contact_ids
      @contact_index = contact_ids.find_index(contact.id)
    end

    def next
      contact_ids[contact_index + 1]
    end

    def previous
      unless contact_index == 0
        contact_ids[contact_index - 1]
      end
    end
  end
end

app/views/contacts/_contact.html.haml
%div[contact]
  %div{ id: "contact-map", class: "contact__map", data: { address: contact.full_address}  }
  .flex.items-center.justify-center
    - if contact.previous
      = link_to contact_path(contact.previous) do
        %i.fa.fa-arrow-circle-o-left.pr-2.text-xl
    .font-bold.text-center.text-4xl.my-2= contact.name
    - if contact.next
      = link_to contact_path(contact.next) do
        %i.fa.fa-arrow-circle-o-right.pl-2.text-xl

  .xl:flex
    %div{ class: "flex w-full" }
      .p-2.flex.flex-auto
        .bg-white.flex-auto.p-2.border-mid
          %h3.mb-2 Edit Details
          = render "form", contact: contact

    %div{ class: "flex w-full" }
      .p-2.flex.flex-auto
        .bg-white.flex-auto.p-2.border-mid
          .h2 Associatied Mailing List
          %ul
            - contact.mailing_lists.each do |list|
              %li.py-2= link_to list.title, list

    %div{ class: "flex w-full" }
      .p-2.flex.flex-auto
        .bg-white.flex-auto.p-2.border-mid
          .h2 Versions
          - contact.versions.each do |version|
            .pt-2.pb-1.text-sm
              .block
                .flex.items-center
                  .w-1.h-1.bg-teal.rounded-full
                  .pl-2.text-black= "Updated #{version.created_at.strftime("%b - %Y")}"
                .pl-3
                  .pt-1= version.street_1
                  - if version.street_2
                    .pt-1= version.street_2
                  .pt-1= "#{version.city}, #{version.state} #{version.zipcode}"

app/views/contacts/_contact_table_row.html.haml
%tr[contact]
  %td
    = link_to contact.name, contact
  %td= contact.street_1
  %td= contact.city
  %td= contact.zipcode

app/views/contacts/_contact_table_template.html.erb
<script>
  window.__contacts__ = <%= raw contacts.to_json(methods: [:address]) %>;
</script>

<div id="contacts-vue-table">
  <contact-table></contact-table>
</div>

<script id="contacts-table-template" type="text/x-template">
  <table class="table-light">
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
      </tr>
    </thead>
    <tbody>
      <contact-table-row v-for="(contact, index) in contacts" v-bind:contact="contact" :key="contact.id">
      </contact-table-row>
    </tbody>
  </table>
</script>

<script id="contact-table-row" type="text/x-template">
  <tr class='contact' id='contact_370'>
    <td>
      <a v-bind:href="contactUrl">{{ contact.name }}</a>
    </td>
    <td>{{contact.address}}</td>
  </tr>
</script>

<script>
  Vue.component('contact-table-row', {
    template: "#contact-table-row",
    props: ["contact"],
    data: function(){
      return {
        contactUrl: "/contacts/" + this.contact.id,
      }
    }
  });

  Vue.component('contact-table', {
    template: "#contacts-table-template",
    props: ["initialContacts"],
    data: function(){
      return {
        contactCount: 0,
        contacts: window.__contacts__,
      }
    }
  });

  new Vue({
    el: "#contacts-vue-table",
  });


</script>

app/views/contacts/_form.html.haml
= form_for contact do |f|
  .sm-col-6
    = f.text_field :name, placeholder: "Enter Contact Name", class: "field"
    = f.text_field :street_1, placeholder: "Street", class: "field"
    = f.text_field :street_2, placeholder: "APT", class: "field"
    = f.text_field :city, placeholder: "City", class: "field"
    = f.text_field :state, placeholder: "State", class: "field"
    = f.text_field :zipcode, placeholder: "Zipcode", class: "field"
    .flex
      = f.button "Save", class: "btn-primary"
      - if contact.persisted?
        .ml-auto
          = link_to "Remove", contact, method: :delete, class: "btn-negative"

app/views/contacts/index.html.haml
.flex.items-center
  .font-bold.mr-2.pb-2.text-4xl Contacts
  = link_to "+", new_contact_path, class: "border h-8 flex items-center justify-center no-underline rounded-full text-grey text-xl w-8"

.flex.flex-col.lg:flex-row
  .existing-contacts.flex-auto
    .text-md
      = "Total: #{contacts.size}"
    #contacts-table
    =# render "contact_table_template", contacts: contacts
  .new-contacts.pl2
    .new-contacts__form
      .h3.mb2 New Contacts
      = form_for ContactUpload.new do |f|
        .pb1
          = f.file_field :csv_upload_file
        .pb1
          = f.button "Upload", class: "btn"
    .new-contacts__recent-uploads.mt2
      .h3.mb2 Recent Uploads
      - if last_upload
        = link_to "Undo Last Upload",
          upload_path(last_upload),
          method: :delete
      .h5.mb1
        %ul.list-reset
          - recent_uploads.each do |upload|
            %li.upload.flex.pr2.mb1{ data: { behavior: "show-included-contacts", contact_ids: upload.contact_ids.join(",") } }
              .upload__date.flex-auto.flex.items-center= upload.uploaded_at
              = link_to upload, class: "upload__undo", method: :delete do
                %i.fa.fa-undo{ aria_hidden: "true"}

app/views/contacts/new.html.haml
= render "form", contact: contact

app/views/contacts/show.html.haml
= render contact

app/views/contacts/show.js.erb
window.modal.showWithHTML("<%= j(render contact) %>");