config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :mailing_lists, only: [:new, :create], path: "mailing-lists"
  end
  resources :contacts
  resources :contact_uploads, only: :create
  resources :uploads, only: :destroy
  resources :mailing_lists, only: :show, path: "mailing-lists"
  resources :mailing_list_contacts, only: [:create, :update], path: "mailing-list-contacts"
  resource :mailing_list_contacts_toggle, only: [:update], path: "mailing-list-contacts-toggle"

  root to: "events#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TML2</title>
    <%= csrf_meta_tags %>

    <link rel="apple-touch-icon" href="touch-icon-iphone.png">
    <meta name="turbolinks-cache-control" content="no-cache">
    <meta name = "viewport" content = "user-scalable=no, width=device-width">
    <%= stylesheet_link_tag "//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= stylesheet_pack_tag 'tailwind' %>
    <%= javascript_pack_tag "hello_elm" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script
      src="<%= Rails.env.development? ? 'https://cdn.jsdelivr.net/npm/vue@2.5.13/dist/vue.js' : 'https://cdn.jsdelivr.net/npm/vue@2.5.13/dist/vue.min.js' %>"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBpSGgeIAvFnUCaElu5qfPIKrIYjnZN6J4"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="md:flex">
      <nav class="bg-dark flex flex-none md:flex-col items-center p-2 text-md">
        <%= link_to root_path, class: "p1 flex mr-auto md:flex-initial md:h-12 md:w-full home__icon no-underline" do %>
          <i class="fa fa-home m-auto" aria-hidden="true"></i>
        <% end %>
        <%= link_to new_event_path, class: "p-1 c-light flex md:h-12 md:w-full no-underline" do %>
          <span class="m-auto">New Event</span>
        <% end %>
        <%= link_to contacts_path, class: "p-1 c-light flex md:h-12 md:w-full no-underline" do %>
          <span class="m-auto">Contacts</span>
        <% end %>
      </nav>
      <section class="min-h-screen p-2 bg-light flex-auto">
        <%= yield %>
      </section>
    </section>
    <div id="contact-modal-container" v-bind:class="{show: showModal}" class="modal-overlay flex items-center justify-center">
      <div class="modal m-4 sm:mx-auto" data-behavior='modal'>
        <div class="modal__close flex items-center justify-center" @click=" showModal = false " data-behavior="modal-close">
          <span>&times</span>
        </div>
        <div id="contact-card__map" class="contact-card__header">
        </div>
        <div class="contact-card__body text-center mb-2">
          <div class="contact-card__user-icon c-light">
            <i class="fa fa-user-circle" aria-hidden="true"></i>
          </div>
          <div v-show="isLoading" class="modal__spinner--overlay flex items-center justify-center">
            <%= image_tag('loader.gif', class: 'modal__spinner ma' ) %>
          </div>
          <h1 class="contact__name bold fs-3">{{ contact.name }}</h1>
          <h1 class="text-lg sm:text-3xl">{{contact.street_1}}</h1>
          <h2 v-if="contact.street_2">{{contact.street_2}}</h2>
          <h1 class="text-lg sm:text-3xl">{{contact.city}}, {{contact.state}} {{contact.zipcode}}</h1>
          <div class="mt-2">
            <button class="btn" @click="copyAddress(contact)">Copy Address</button>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>